/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dadatoolkit_android_view_GestureDetectorNative */

#ifndef _Included_com_dadatoolkit_android_view_GestureDetectorNative
#define _Included_com_dadatoolkit_android_view_GestureDetectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dadatoolkit_android_view_GestureDetectorNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dadatoolkit_android_view_GestureDetectorNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_dadatoolkit_android_view_GestureDetectorNative
 * Method:    getSupportedEngine
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_dadatoolkit_android_view_GestureDetectorNative_getSupportedEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_dadatoolkit_android_view_GestureDetectorNative
 * Method:    getEngineVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dadatoolkit_android_view_GestureDetectorNative_getEngineVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_dadatoolkit_android_view_GestureDetectorNative
 * Method:    getResult
 * Signature: (ILandroid/view/MotionEvent;Landroid/os/Bundle;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dadatoolkit_android_view_GestureDetectorNative_getResult
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     com_dadatoolkit_android_view_GestureDetectorNative
 * Method:    hasSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dadatoolkit_android_view_GestureDetectorNative_hasSupported
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
