/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dadatoolkit_android_graphic_BitmapEngine */

#ifndef _Included_com_dadatoolkit_android_graphic_BitmapEngine
#define _Included_com_dadatoolkit_android_graphic_BitmapEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dadatoolkit_android_graphic_BitmapEngine
 * Method:    nativeEffect
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dadatoolkit_android_graphic_BitmapEngine_nativeEffect
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
